name: "chatservice"
data_dir: "./data-log/"
shutdown_grace_sec: 5

app:
  env: "debug"  # the value same as gin mode (debug, release, test)
  addr: 8896
  use_multipoint: false
  load_front: false
  load_swagger: true

logger:
  stdout: false
  level: "debug"
  file: "./data-log/logfile.log"
  rotation: true
  max_size: 128

socket:
  server_key: "defaultkey"
  port: 8896
  address: ""
  single_socket: true

database:
  driver_name: "postgres"
  default_db_idx: 0
  conn_info:
    - "host=172.99.0.12 port=5432 user=postgres dbname=dcc_chat password=123456 sslmode=disable"    # for local
