name: "monitorservice"
data_dir: "./data-log/"
shutdown_grace_sec: 5

app:
  env: "debug"  # the value same as gin mode (debug, release, test)
  addr: 17782
  use_multipoint: false
  load_front: false
  load_swagger: true
  is_verify_captcha: true

logger:
  stdout: false
  level: "debug"
  file: "./data-log/logfile.log"
  rotation: true
  max_size: 128

socket:
  server_key: "defaultkey"
  port: 17783
  address: ""
  single_socket: true

jwt:
  encrypt_string: "#oHBda8jidas32R3G$Op"
  issuer: "monitorservice"
  expire_time_min: 10080

captcha:
  # Digit
  key_length: 6
  img_width: 400
  img_height: 90
  gc_limit_number: 10240
  ExpiredSec: 3600

database:
  driver_name: "postgres"
  default_db_idx: 0
  conn_info:
    - "host=127.0.0.1 port=5432 user=postgres dbname=monitor password=123456 sslmode=disable"    # for local
    # - "host=172.99.0.12 port=5432 user=postgres dbname=order password=123456 sslmode=disable"    # for docker
